// <auto-generated />
using System;
using CadastroFuncionarios.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadastroFuncionarios.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816040110_InicialTPH")]
    partial class InicialTPH
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("CadastroFuncionarios.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataContratacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoFuncionario")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");

                    b.HasDiscriminator<string>("TipoFuncionario").HasValue("Funcionario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CadastroFuncionarios.Models.Desenvolvedor", b =>
                {
                    b.HasBaseType("CadastroFuncionarios.Models.Funcionario");

                    b.Property<int>("CertificacoesQtd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivelSenioridade")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Desenvolvedor");
                });

            modelBuilder.Entity("CadastroFuncionarios.Models.Estagiario", b =>
                {
                    b.HasBaseType("CadastroFuncionarios.Models.Funcionario");

                    b.Property<decimal>("AuxilioTransporte")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Estagiario");
                });

            modelBuilder.Entity("CadastroFuncionarios.Models.Gerente", b =>
                {
                    b.HasBaseType("CadastroFuncionarios.Models.Funcionario");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("TEXT");

                    b.Property<int>("TamanhoEquipe")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Gerente");
                });
#pragma warning restore 612, 618
        }
    }
}
